### ISSUE TITLE
Generator produces wrong code for UnaryExpression

### ISSUE THREAD

**Issue by asakura** [bryanjos/elixir-estree#14]
1) Builder.binary_expression(:==, Builder.unary_expression(:!, true, Builder.literal(:x)), Builder.literal(1)))
2) Builder.unary_expression(:!, true, Builder.binary_expression(:==, Builder.literal(:x), Builder.literal(1)))

Both variants produces absolutely same ES program: !x == 1

The second AST should produce: !(x == 1)

I can't imagine all possible argument variants, when unary_expression should wrap it in parentheses, but probably it must work in the same way for LogicalExpression too.

**Comment by bryanjos** [comment]
Good catch. My first thought is maybe to use parenthesis every time. My next thought is to maybe use parenthesis every time for a subset of the unary operators where this could happen. Or maybe just add parenthesis if it is given an expression?

**Comment by bryanjos** [comment]
closed by #15
